{{- if and .Values.app.enabled (eq .Values.app.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{.Values.app.namespace}}
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}
