{{- if and .Values.k6.enabled (eq .Values.k6.enabled true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6-runner
  namespace: testing
---
apiVersion: v1
kind: Secret
metadata:
  name: k6-runner
  annotations:
    kubernetes.io/service-account.name: k6-runner
  namespace: testing
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k6-runner
  namespace: testing
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-runner
  namespace: testing
subjects:
  - kind: ServiceAccount
    name: k6-runner
roleRef:
  kind: Role
  name: k6-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
