{{- if and .Values.app.enabled (eq .Values.app.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{.Values.app.namespace}}
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.app.nginx.image }}:{{ .Values.app.nginx.tag }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
{{- end }}
