{{- if and .Values.k6.enabled (eq .Values.k6.enabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name: react-demo-app-secret
  namespace: testing
type: Opaque
stringData:
  APP_URL: https://react-demo.gluki.io
  APP_TOKEN: xxx
{{- end }}
