{{- if and .Values.k6 (hasKey .Values.k6 "enabled") (eq .Values.k6.enabled true) }}
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: react-demo-loadtest-1
  namespace: testing
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    runTriggeredAt: "2025-08-28T14:20:00Z"
spec:
  script:
    configMap:
      name: react-demo-loadtest-script
      file: script.js
  parallelism: 3
  arguments: -o experimental-opentelemetry --tag testid=react-demo
  runner:
    env:
      - name: K6_OTEL_EXPORTER_TYPE
        value: "grpc"
      - name: K6_OTEL_GRPC_EXPORTER_INSECURE
        value: "true"
      - name: K6_OTEL_GRPC_EXPORTER_ENDPOINT
        value: "opentelemetry-collector.observability.svc.cluster.local:4317"
      - name: K6_OTEL_SERVICE_NAME
        value: "k6-load-test"
      - name: K6_OTEL_METRIC_PREFIX
        value: "k6_"
    envFrom:
      - secretRef:
          name: react-demo-app-secret
{{- end }}
